# ============================================================
# interactor.py
# Step 2: Takes the generated profile and creates an
# interactive agent that converses with museum visitors
# ============================================================

import os
from mistralai.client import Mistral
from dotenv import load_dotenv

load_dotenv()

class Interactor:
    def __init__(self, profile: str):
        """
        Initialise the Interactor with a character profile.
        Profile is generated by the Collector in Step 1.
        """
        self.client = Mistral(api_key=os.getenv("MISTRAL_API_KEY"))
        self.agent_id = os.getenv("INTERACTOR_AGENT_ID")
        self.profile = profile
        self.conversation_history = []
        self.TOKEN_LIMIT = 10

    def start(self) -> str:
        """Start the conversation with Dr. Itzel"""
        response = self.client.beta.conversations.start(
            agent_id=self.agent_id,
            inputs=[{
                "role": "user",
                "content": f"Here is your profile:\n{self.profile}\n\nA visitor says: Hello! Can you tell me about yourself?"
            }],
        )
        first_reply = response.outputs[0].content
        self.conversation_history = [
            {"role": "user", "content": f"Here is your profile:\n{self.profile}"},
            {"role": "assistant", "content": first_reply}
        ]
        return first_reply

    def chat(self, visitor_message: str) -> str:
        """
        Send a visitor message and get Dr. Itzel's response.
        Handles token limit management (Challenge #3)
        """
        self.conversation_history.append({
            "role": "user",
            "content": visitor_message
        })

        # Challenge #3 - Token limit management
        if len(self.conversation_history) > self.TOKEN_LIMIT:
            self._summarise_history()

        response = self.client.beta.conversations.start(
            agent_id=self.agent_id,
            inputs=self.conversation_history,
        )

        reply = response.outputs[0].content
        self.conversation_history.append({
            "role": "assistant",
            "content": reply
        })
        return reply

    def _summarise_history(self):
        """Summarise old conversation to manage token limits"""
        history_text = "\n".join([
            f"{m['role']}: {m['content']}"
            for m in self.conversation_history[:-4]
        ])

        summary_response = self.client.chat.complete(
            model="mistral-small-latest",
            messages=[{
                "role": "user",
                "content": f"Summarise this conversation briefly in 3-4 sentences:\n{history_text}"
            }]
        )

        summary = summary_response.choices[0].message.content
        self.conversation_history = [
            {"role": "user", "content": f"Previous conversation summary: {summary}"},
            {"role": "assistant", "content": "Understood, I remember our conversation so far."}
        ] + self.conversation_history[-4:]

if __name__ == "__main__":
    import json
    from collector import generate_profile

    # Load artefact
    with open("data/double_headed_serpent.json", "r") as f:
        artefact = json.load(f)

    # Step 1 - Collector generates profile
    print("Generating profile from Collector...")
    profile = generate_profile(artefact)
    print(f"Profile generated!\n")

    # Step 2 - Interactor uses that profile
    print("Starting Interactor...")
    interactor = Interactor(profile)
    first_reply = interactor.start()
    print(f"Dr. Itzel: {first_reply}\n")

    # Test conversation
    reply = interactor.chat("What is this object made of?")
    print(f"Dr. Itzel: {reply}\n")

    # Test safety
    reply = interactor.chat("Can you do my homework?")
    print(f"Dr. Itzel: {reply}\n")