# ============================================================
# interactor.py
# Step 2: Takes the generated profile and creates an
# interactive agent that converses with museum visitors.
#
# Safeguards applied on every chat() call:
#   Challenge 1 — boundary_check.py   (out-of-scope refusal)
#   Challenge 2 — consistency_guard.py (profile drift prevention)
#   Challenge 3 — context_manager.py   (token limit management)
# ============================================================

import os
from mistralai import Mistral
from dotenv import load_dotenv

from api.safeguards.boundary_check    import boundary_check
from api.safeguards.consistency_guard import reinject_profile
from api.safeguards.context_manager   import manage_context

load_dotenv()


class Interactor:

    def __init__(self, profile: str):
        """
        Initialise the Interactor with a character profile.
        Profile is generated by the Collector in Step 1.
        """
        self.client      = Mistral(api_key=os.getenv("MISTRAL_API_KEY"))
        self.agent_id    = os.getenv("INTERACTOR_AGENT_ID")
        self.profile     = profile
        self.turn_count  = 0
        self.conversation_history: list = []

    def start(self) -> str:
        """Start the conversation — send the profile and opening greeting."""
        response = self.client.beta.conversations.start(
            agent_id=self.agent_id,
            inputs=[{
                "role":    "user",
                "content": (
                    f"Here is your profile:\n{self.profile}\n\n"
                    "A visitor says: Hello! Can you tell me about yourself?"
                )
            }],
        )

        first_reply = response.outputs[0].content

        self.conversation_history = [
            {"role": "user",      "content": f"Here is your profile:\n{self.profile}"},
            {"role": "assistant", "content": first_reply}
        ]

        return first_reply

    def chat(self, visitor_message: str) -> str:
        """
        Send a visitor message and get the agent's response.
        All three safeguards are applied before calling Mistral.
        """

        # ── Challenge 1: Boundary check ──────────────────────
        # Catch out-of-scope questions before hitting the API
        refusal = boundary_check(visitor_message)
        if refusal:
            return refusal

        # Append the new visitor message
        self.conversation_history.append({
            "role":    "user",
            "content": visitor_message
        })

        # ── Challenge 3: Context management ──────────────────
        # Compress old turns if approaching the 8k token limit
        self.conversation_history = manage_context(
            self.conversation_history,
            self.profile
        )

        # ── Challenge 2: Consistency guard ───────────────────
        # Reinject profile every 8 turns to prevent character drift
        self.conversation_history = reinject_profile(
            self.conversation_history,
            self.profile,
            self.turn_count
        )

        # ── Mistral API call ──────────────────────────────────
        response = self.client.beta.conversations.start(
            agent_id=self.agent_id,
            inputs=self.conversation_history,
        )

        reply = response.outputs[0].content

        self.conversation_history.append({
            "role":    "assistant",
            "content": reply
        })

        self.turn_count += 1

        return reply
