# ============================================================
# main_group.py
# Flask backend that connects KH's individual agent to the
# AutoGame-copy group frontend.
#
# Uses the group project's agent names and artefact data,
# but runs KH's own Collector, Interactor, and Safeguards
# under the hood.
#
# Reads from cache (generated by generate_agents.py) for
# instant loading — no live generation delays.
#
# Run alongside main.py on a different port:
#   python api/main_group.py  → port 5005
# ============================================================

import os
import json
import re
from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS
from dotenv import load_dotenv
from collector import generate_profile
from interactor import Interactor

load_dotenv()

app = Flask(__name__)
CORS(app)

sessions = {}

# ── Paths ───────────────────────────────────────────────────
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

CACHE_FILE = os.path.join(BASE_DIR, "data", "cached_agents.json")

GROUP_STORY = os.path.join(
    BASE_DIR, "..", "AutoGame-copy", "frontend", "public", "story"
)

GROUP_FRONTEND = os.path.join(
    BASE_DIR, "..", "AutoGame-copy", "frontend", "public"
)

# ── Cache keys for the group's artefacts ───────────────────
# These match the keys saved by generate_agents.py
GROUP_CACHE_KEYS = {
    0: "museum-experience_10",   # Magdeburg Ivories
    1: "museum-experience_11",   # Rosetta Stone
}


def load_cache() -> dict:
    if os.path.exists(CACHE_FILE):
        with open(CACHE_FILE, "r") as f:
            return json.load(f)
    return {}


def load_collections(storyname: str) -> list:
    path = os.path.join(GROUP_STORY, storyname, "collections.json")
    if not os.path.exists(path):
        raise FileNotFoundError(f"collections.json not found: {path}")
    with open(path, "r") as f:
        data = json.load(f)
    return data.get("items", [])


def get_agent_name(storyname: str, event_index: int) -> str:
    """Get the group project's agent name for this artefact."""
    try:
        items = load_collections(storyname)
        for item in items:
            if item.get("eventIndex") == event_index:
                return item.get("agentName")
    except Exception as e:
        print(f"Could not load agent name: {e}")
    return None


def get_wikipedia_url(storyname: str, event_index: int) -> str:
    try:
        items = load_collections(storyname)
        for item in items:
            if item.get("eventIndex") == event_index:
                return item.get("wikipediaUrl")
    except Exception:
        pass
    return None


def load_artefact_from_event(storyname: str, event_index: int) -> dict:
    """Fallback: load artefact from group event.json if not in cache."""
    event_path = os.path.join(GROUP_STORY, storyname, "event.json")
    if not os.path.exists(event_path):
        raise FileNotFoundError(f"event.json not found: {event_path}")

    with open(event_path, "r") as f:
        data = json.load(f)

    events = data.get("event", [])
    if event_index >= len(events):
        raise ValueError(f"Event index {event_index} out of range.")

    event    = events[event_index]
    artifact = event.get("artifact", {})

    return {
        "title":            artifact.get("name", "Unknown"),
        "summary":          artifact.get("description", ""),
        "current_location": artifact.get("current_location", ""),
        "materials":        artifact.get("material", ""),
        "origin":           artifact.get("origin", ""),
        "created":          artifact.get("date", ""),
        "infobox_raw":      json.dumps(artifact),
    }


def extract_name_from_profile(profile: str) -> str:
    try:
        data = json.loads(profile)
        if isinstance(data, dict) and "name" in data:
            return data["name"]
    except Exception:
        pass
    match = re.search(r'"name"\s*:\s*"([^"]+)"', profile)
    return match.group(1) if match else None


# ── Routes ──────────────────────────────────────────────────

@app.route("/")
def index():
    return send_from_directory(GROUP_FRONTEND, "index.html")


@app.route("/init-conversation", methods=["POST"])
def init_conversation():
    try:
        data        = request.get_json()
        storyname   = data.get("storyname", "museum-experience")
        event_index = int(data.get("event_index", 0))
        agent       = data.get("agent", "Museum Guide")

        # Get the group's agent name and wiki URL from collections.json
        group_agent_name = get_agent_name(storyname, event_index)
        wiki_url         = get_wikipedia_url(storyname, event_index)

        print(f"\n{'='*50}")
        print(f"Group frontend request: {storyname} index {event_index}")
        print(f"Group agent name: {group_agent_name}")

        # ✅ Try cache first
        cache     = load_cache()
        cache_key = GROUP_CACHE_KEYS.get(event_index)
        
        if cache_key and cache_key in cache:
            print(f"Cache hit: {cache_key} — loading instantly")
            cached    = cache[cache_key]
            artefact  = cached["artefact"]
            profile   = cached["profile"]
            image_url = cached.get("image_url")
        else:
            # ⚠️ Cache miss — generate live (slow)
            print(f"Cache miss — generating live for event_index {event_index}")
            artefact  = load_artefact_from_event(storyname, event_index)
            result    = generate_profile(artefact)
            profile   = result["profile"]
            image_url = result["image_url"]

        # Inject group agent name so KH interactor speaks as that character
        if group_agent_name:
            profile = (
                f"Your name is {group_agent_name}. "
                f"You must always refer to yourself as {group_agent_name}.\n\n"
                + profile
            )

        character_name = group_agent_name or extract_name_from_profile(profile) or "Museum Guide"

        # Start KH Interactor with all 3 safeguards
        interactor  = Interactor(profile)
        first_reply = interactor.start()

        session_id = f"{storyname}_{event_index}_{agent}"
        sessions[session_id] = {
            "artefact":       artefact,
            "profile":        profile,
            "interactor":     interactor,
            "agent":          agent,
            "image_url":      image_url,
            "character_name": character_name,
            "wiki_url":       wiki_url,
        }

        print(f"✅ KH Interactor started as: {character_name}")

        return jsonify({
            "response":        first_reply,
            "conversation_id": session_id,
            "image_url":       image_url,
            "character_name":  character_name,
            "wiki_url":        wiki_url,
        })

    except Exception as e:
        print(f"Error in init_conversation: {e}")
        return jsonify({"error": str(e)}), 500


@app.route("/response", methods=["POST"])
def response():
    try:
        data            = request.get_json()
        user_message    = (data.get("response") or "").strip()
        conversation_id = data.get("conversation_id")

        if not conversation_id or conversation_id not in sessions:
            return jsonify({"error": "Session not found"}), 404
        if not user_message:
            return jsonify({"error": "Empty message"}), 400

        interactor = sessions[conversation_id]["interactor"]
        reply      = interactor.chat(user_message)

        return jsonify({
            "response":        reply,
            "conversation_id": conversation_id
        })

    except Exception as e:
        print(f"Error in response: {e}")
        return jsonify({"error": str(e)}), 500


@app.route("/evaluate-agent", methods=["POST"])
def evaluate_agent():
    try:
        data            = request.get_json()
        conversation_id = data.get("conversation_id")

        if conversation_id not in sessions:
            return jsonify({"error": "Session not found"}), 404

        session = sessions[conversation_id]

        from evaluation_pipeline.run_evaluation import run_full_evaluation
        results = run_full_evaluation(
            session["interactor"],
            session["artefact"]
        )

        return jsonify({
            "status":          "success",
            "conversation_id": conversation_id,
            "evaluation":      results
        })

    except Exception as e:
        print(f"Error in evaluate_agent: {e}")
        return jsonify({"error": str(e)}), 500


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "running", "mode": "group-integration"})


@app.route("/agent-images/<path:filename>")
def agent_images(filename):
    images_dir = os.path.join(BASE_DIR, "data", "images")
    return send_from_directory(images_dir, filename)


@app.route("/story/<path:filename>")
def story_assets(filename):
    """Serve the group project's story assets (images, json etc.)"""
    story_dir = os.path.join(GROUP_FRONTEND, "story")
    return send_from_directory(story_dir, filename)


if __name__ == "__main__":
    cache = load_cache()
    print("Starting KH Museum Agent — Group Integration Mode")
    print(f"Cache: {'✅ loaded' if cache else '❌ not found — will generate live'}")
    print(f"Group artefacts in cache: {sum(1 for k in GROUP_CACHE_KEYS.values() if k in cache)}/{len(GROUP_CACHE_KEYS)}")
    print("Running on port 5004")
    app.run(host="0.0.0.0", port=5004, debug=True)